var Home = (function() {

	var myFirebaseRef = new Firebase("https://practicesafebrowsing.firebaseIO.com");

	var homeData = {
		title: 'Practice Safe Browsing',
		desc: 'Your online activity is being monitored, tracked and recorded. It’s time you take back your privacy with tools that do just that.'
	};

	var faqData = {
		title: 'Frequently Asked Questions',
		list: [
				{
					question: 'What\'s the deal?',
					answer: 'Privacy and security online is our basic right that’s being breached. That’s why we’ve currated a list of tools to help keep you safe online.'
				},
				{
					question: 'Why do I care?',
					answer: 'Your activity on the web is being monitored, tracked, and recorded. Whether it’s government, advertisers or hackers your information is being captured and that’s not good.'
				},
				{
					question: 'Have nothing to hide?',
					answer: 'Not only can your pattern of life be deduced from the metadata generated by your online habits, but everyone has something to hide. Would you give a stranger your bank account information?'
				}
		]
	};

	var submitData = {
		title: 'Submit a tool',
		desc: 'If you know a tool that should be added to our list, send a tweet to @climbrick.'
	};


	// Partials
	var homePartial = $('#partial-banner-home').html();
		infoPartialCompiled = _.template( homePartial );

	var faqPartial = $('#partial-banner-faq').html();
		faqPartialCompiled = _.template( faqPartial );	

	var submitPartial = $('#partial-banner-submit').html();
		submitPartialCompiled = _.template( submitPartial );

	var toolsPartial =$('#partial-tools').html();
		toolsPartialCompiled = _.template( toolsPartial );

	// DOM Handlers

	$('#nav-home').click(function() {
		$('#banner').html(infoPartialCompiled( homeData ));
	});

	$('#nav-faq').click(function() {
		$('#banner').html(faqPartialCompiled( faqData ));
	});

	$('#nav-submit').click(function() {
		$('#banner').html(submitPartialCompiled( submitData ));
	});

	myFirebaseRef.orderByKey().on("child_added", function(snapshot) {
		console.log(snapshot.key());
	});

	

	// KICKSTART VIEW
	function initHome() {

		// load banner content
		$('#banner').html(infoPartialCompiled( homeData ));

		// load main content
		$('#main-content').html(toolsPartialCompiled());

		// bind events

	}
	return {
		init: initHome
	};

})();
