var Home = (function() {

	var myFirebaseRef = new Firebase("https://practicesafebrowsing.firebaseIO.com");

	var homeData = {
		title: 'Practice Safe Browsing',
		desc: 'Your online activity is being monitored, tracked and recorded. It’s time you take back your privacy with tools that do just that.'
	};

	var faqData = {
		title: 'Frequently Asked Questions',
		list: [
				{
					question: 'What\'s the deal?',
					answer: 'Privacy and security online is our basic right that’s being breached. That’s why we’ve currated a list of tools to help keep you safe online.'
				},
				{
					question: 'Why do I care?',
					answer: 'Your activity on the web is being monitored, tracked, and recorded. Whether it’s government, advertisers or hackers your information is being captured and that’s not good.'
				},
				{
					question: 'Have nothing to hide?',
					answer: 'Not only can your pattern of life be deduced from the metadata generated by your online habits, but everyone has something to hide. Would you give a stranger your bank account information?'
				}
		]
	};

	var submitData = {
		title: 'Submit a tool',
		desc: 'If you know a tool that should be added to our list, send a tweet to @climbrick.'
	};


	var filterData = {
		toolList: [
				{
					name: 'toolName',
					desc: "lorem ipsum dolar sit amet",
					icon: "assets/icon_disconnect.png",
					url: "#"
				}
		]
	};


	// Partials
	var homePartial = $('#partial-banner-home').html();
		infoPartialCompiled = _.template( homePartial );

	var faqPartial = $('#partial-banner-faq').html();
		faqPartialCompiled = _.template( faqPartial );	

	var submitPartial = $('#partial-banner-submit').html();
		submitPartialCompiled = _.template( submitPartial );

	var toolsPartial =$('#partial-tools').html();
		toolsPartialCompiled = _.template( toolsPartial );


	// DOM Handlers

	$('body').on('click','#nav-home', function(e) {
		e.preventDefault();

		$('#banner').html(infoPartialCompiled( homeData ));
	});

	$('body').on('click','#nav-faq', function(e) {
		e.preventDefault();

		$('#banner').html(faqPartialCompiled( faqData ));
	});

	$('body').on('click','#nav-submit', function(e) {
		e.preventDefault();

		$('#banner').html(submitPartialCompiled( submitData ));
	});

	// Filter navigation buttons

	$('body').on('click', '#filter-browser', function(e) {
		e.preventDefault();

		filterToSelect = "browser";
	});

	$('body').on('click', '#filter-chat', function(e) {
		e.preventDefault();
		
		filterToSelect = "chat";
	});

	$('body').on('click', '#filter-email', function(e) {
		e.preventDefault();

		filterToSelect = "email";
	});

	$('body').on('click', '#filter-encryption', function(e) {
		e.preventDefault();

		filterToSelect = "encryption";
	});

	$('body').on('click', '#filter-os', function(e) {
		e.preventDefault();

		filterToSelect = "os";
	});

	$('body').on('click', '#filter-storage', function(e) {
		e.preventDefault();

		filterToSelect = "storage";
	});



	var filterToSelect = "all";

	// Retrieving data from Firebase
	myFirebaseRef.once("value", function(snapshot) {
		var data = snapshot.val();
		
		for( var filter in data ) {
			if ( filter !== filterToSelect ) {
				continue;
			}

		    var currentFilter = data[ filter ];
		    // console.log( currentFilter );
		    
		    for( var item in currentFilter ) {
		    	var toolName = (currentFilter[ item ].name);
		    	var toolIcon = (currentFilter[ item ].icon);
		    	var toolDesc = (currentFilter[ item ].desc);

		    	console.log( toolName, toolIcon, toolDesc );
		    	

		        // console.log( item, currentFilter[ item ], filter );
		        // you can access stuff like currentFilter[ item ].desc here
		    }
		}
	});


	// KICKSTART VIEW
	function initHome() {

		// load banner content
		$('#banner').html(infoPartialCompiled( homeData ));

		// load main content
		$('#main-content').html(toolsPartialCompiled( filterData ));

		// bind events

	}
	return {
		init: initHome
	};

})();
